# Generated by Django 4.2.2 on 2023-08-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario_articulo_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen_perfil',
            field=models.ImageField(default='blog/terminator-perfil1.jpg', upload_to='perfil/'),
        ),
    ]
