# Generated by Django 4.2.2 on 2023-08-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen_perfil',
            field=models.ImageField(default='blog/img/terminator-perfil1.jpg', upload_to='perfil/'),
        ),
    ]
